name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  schedule:
    - cron: "0 17 * * *" # Runs at 17:00 UTC every day.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: thinh19981998
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
